### ISSUE TITLE
Mincblur is missing

### ISSUE THREAD

**Issue by SaibotMagd** [carlohamalainen/volgenmodel-nipype#5]
After I tested the new install pipeline, it seems to run further, but now there's no mincblur function. I think this is part of minctools v2 and have to be installed separatly:

```
Standard error:
Can't exec "mincblur": No such file or directory at /usr/local/bin/mincnorm line 222.
Died at /usr/local/bin/mincnorm line 222.
Return code: 2

210727-09:35:08,621 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 80.00/80.00, Free processors: 8/8.
210727-09:35:10,618 nipype.workflow INFO:
	 ***********************************
210727-09:35:10,618 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,618 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise0-b54cc34a-410a-4104-924c-edfb9a586b92.pklz
210727-09:35:10,619 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,619 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise1-1a479b81-426d-429e-93d5-ff7d8e5b7a0e.pklz
210727-09:35:10,619 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,619 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise2-4fbef6f9-9863-4fd5-80a9-90c253d5ebe4.pklz
210727-09:35:10,619 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,619 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise3-b29c453c-3fbc-48e7-8aae-3f3cdc89eebb.pklz
210727-09:35:10,620 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,620 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise4-1746570d-0b8e-4add-8b47-f0794603c90f.pklz
210727-09:35:10,620 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,620 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise5-7c303db9-8118-4aa5-91a4-2df5db342f80.pklz
210727-09:35:10,620 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,620 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise6-9c39f491-4110-4a3e-9922-6d5d64aa86f4.pklz
210727-09:35:10,621 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,621 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise7-7b7fde07-c0ca-4818-af98-e7a6faf1cebb.pklz
210727-09:35:10,621 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,621 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093508-saibotmagd-_preprocess_normalise8-5553dbc2-20bf-4ad4-9e46-c3f718010a9d.pklz
210727-09:35:10,621 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "volgenmodel.py", line 920, in <module>
    wf.run(
  File "/home/saibotmagd/anaconda3/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/saibotmagd/anaconda3/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/home/saibotmagd/anaconda3/lib/python3.8/site-packages/nipype/pipeline/plugins/tools.py", line 96, in report_nodes_not_run
    raise RuntimeError(
RuntimeError: Workflow did not execute cleanly. Check log for details

```

**Comment by carlohamalainen** [comment]
No, it's a normal binary in 1.9:

```
$ dpkg -c minc-toolkit-1.9.18-20200813-Ubuntu_20.04-x86_64.deb  | grep mincblur
-rwxr-xr-x root/root    933928 2020-10-03 17:22 ./opt/minc/1.9.18/bin/mincblur
-rw-r--r-- root/root      4427 2016-04-05 03:59 ./opt/minc/1.9.18/man/man1/mincblur.1
```

This is an installation issue on your side, nothing to do with volgenmodel-nipype.

**Comment by SaibotMagd** [comment]
I downloaded the minc-toolkit binary manuelly unpacked it and set the correct paths. Now it runs till the next error arrived. But you're right, this have nothing to do with vmn.
