### ISSUE TITLE
nvoliso Illegal division by zero at NumericUtilities.pm

### ISSUE THREAD

**Issue by SaibotMagd** [carlohamalainen/volgenmodel-nipype#6]
Hi, I successfully ran the "volgenmodel-fast-example", I got this error when I try my own data.
I'm neither a programmer nor linux expert so I can't even say if the problem comes from nipype, minc-toolkit or volgenmodel itself. Sorry if I guessed wrong.

```
{'node': _preprocess_voliso3,
 'traceback': ['Traceback (most recent call last):\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__\n    mp_context=mp_context,\n',
  "TypeError: __init__() got an unexpected keyword argument 'initializer'\n",
  '\nDuring handling of the above exception, another exception occurred:\n\n',
  'Traceback (most recent call last):\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node\n    result["result"] = node.run(updatehash=updatehash)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run\n    result = self._run_interface(execute=True)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface\n    return self._run_command(execute)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command\n    result = self._interface.run(cwd=outdir)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 397, in run\n    runtime = self._run_interface(runtime)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface\n    self.raise_exception(runtime)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception\n    ).format(**runtime.dictcopy())\n',
  'RuntimeError: Command:\nvoliso --avgstep --clobber /home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2/preprocess_volpad/mapflow/_preprocess_volpad3/gerbil_mouse_6_volcentre_norm_volpad.mnc gerbil_mouse_6_volcentre_norm_volpad_voliso.mnc\nStandard output:\n\nStandard error:\n
Illegal division by zero at /home/nistmni/src/minc-toolkit-v2/mni-perllib/MNI/NumericUtilities.pm (autosplit into /home/nistmni/src/build/minc-toolkit-v2/mni-perllib/perl/auto/MNI/NumericUtilities/round.al) line 198.\n
Died at /home/saibotmagd/toolboxes/minc/1.9.18/bin/voliso line 112.\nReturn code: 255\n']}
```

Probably helpful, the convert discription from nii2mnc:

```
<nifti_image
  nifti_type = 'NIFTI-1+'
  header_filename = '/home/saibotmagd/srcImageData/Template_Creation/5543_rigReg_rH.nii'
  image_filename = '/home/saibotmagd/srcImageData/Template_Creation/5543_rigReg_rH.nii'
  image_offset = '352'
  ndim = '3'
  nx = '678'
  ny = '819'
  nz = '448'
  dx = '1'
  dy = '1'
  dz = '1'
  datatype = '4'
  datatype_name = 'INT16'
  nvox = '248766336'
  nbyper = '2'
  byteorder = 'LSB_FIRST'
  scl_slope = '1'
  scl_inter = '0'
  xyz_units = '2'
  xyz_units_name = 'mm'
  qform_code = '2'
  qform_code_name = 'Aligned Anat'
  qto_xyz_matrix = '-1 0 0 -0 0 -1 0 -0 0 0 1 0 0 0 0 1'
  qto_ijk_matrix = '-1 0 0 0 0 -1 0 0 0 0 1 0 0 0 0 1'
  quatern_b = '0'
  quatern_c = '0'
  quatern_d = '1'
  qoffset_x = '-0'
  qoffset_y = '-0'
  qoffset_z = '0'
  qfac = '1'
  qform_i_orientation = 'Right-to-Left'
  qform_j_orientation = 'Anterior-to-Posterior'
  qform_k_orientation = 'Inferior-to-Superior'
  sform_code = '1'
  sform_code_name = 'Scanner Anat'
  sto_xyz_matrix = '-1 0 0 -0 0 -1 0 -0 0 0 1 0 0 0 0 1'
  sto_ijk matrix = '-1 0 0 0 0 -1 0 0 0 0 1 0 0 0 0 1'
  sform_i_orientation = 'Right-to-Left'
  sform_j_orientation = 'Anterior-to-Posterior'
  sform_k_orientation = 'Inferior-to-Superior'
  num_ext = '0'
/>
Using s-form transform:
 -1.0000,   0.0000,   0.0000,  -0.0000, 
  0.0000,  -1.0000,   0.0000,  -0.0000, 
  0.0000,   0.0000,   1.0000,   0.0000, 
  0.0000,   0.0000,   0.0000,   1.0000, 
xspace start:  -0.0000 step:  -1.0000 cosines:   1.0000  -0.0000  -0.0000 flip: 0
yspace start:  -0.0000 step:  -1.0000 cosines:  -0.0000   1.0000  -0.0000 flip: 0
zspace start:   0.0000 step:   1.0000 cosines:   0.0000   0.0000   1.0000 flip: 0
```

**Comment by carlohamalainen** [comment]
I'm not a neuroimaging expert, I can't help for this kind of error :)

My contribution was to port the original Perl scripts to a Nipype workflow and add some wrappers for MINC tools to Nipype. I made sure that the workflow numerically matched the original Perl scripts. Apart from this, I have no experience with the underlying tools in the workflow.

**Comment by SaibotMagd** [comment]
Thx I've got a very good answer in the minc-toolkit package: https://github.com/BIC-MNI/minc-toolkit-v2/issues/138 this is probably helpful for others too.

**Comment by carlohamalainen** [comment]
Interesting! Would need someone like Andrew Janke to work out where to apply this transform to the input files.
